<?php
/**
 * @category Kevin Kucera
 * @package rentalmgr
 * @copyright Copyright (c) 2013 Kevin Kucera
 * @user: kevin
 * @date: 10/29/13
 */

$this->headLink()
    ->appendStylesheet($this->basePath() . '/js/DataTables/media/css/jquery.dataTables_rm.css');

$this->headScript()
    ->appendFile($this->basePath() . '/js/DataTables/media/js/jquery.dataTables.js')
    ->appendFile($this->basePath() . '/js/user/user.dataTable.js')
    ->appendFile($this->basePath() . '/js/acl/acl.user.dataTable.js')
?>
<h1>User ACL Resources</h1>
<div>Select the user you wish to adjust the ACL for.</div>
<table cellpadding="0" cellspacing="0" border="0" class="display" id="user-data-table">
    <thead>
    <tr>
        <th>User ID</th>
        <th width="30%">Name</th>
        <th width="30%">Email</th>
        <th width="20%">Created</th>
        <th width="20%">Modified</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td colspan="4" class="dataTables_empty">Loading data from server</td>
    </tr>
    </tbody>
</table>