<?php
/**
 * @category Kevin Kucera
 * @package rentalmgr
 * @copyright Copyright (c) 2013 Kevin Kucera
 * @user: kevin
 * @date: 10/29/13
 */

$this->headLink()
    ->appendStylesheet($this->basePath() . '/js/DataTables/media/css/jquery.dataTables_rm.css');

$this->headScript()
    ->appendFile($this->basePath() . '/js/DataTables/media/js/jquery.dataTables.js')
    ->appendFile($this->basePath() . '/js/organization/organization.dataTable.js')
?>
<h1>Organizations</h1>
<table cellpadding="0" cellspacing="0" border="0" class="display" id="organization-data-table">
    <thead>
    <tr>
        <th>Organization ID</th>
        <th width="50%">Name</th>
        <th width="20%">Created</th>
        <th width="20%">Modified</th>
        <th width="10%"></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td colspan="5" class="dataTables_empty">Loading data from server</td>
    </tr>
    </tbody>
</table>