<?php
/**
 * @category Kevin Kucera
 * @package rentalmgr
 * @copyright Copyright (c) 2013 Kevin Kucera
 * @user: kevin
 * @date: 10/6/13
 */
?>
<div class="page-title">ACL Management</div>
<div>
ACL stands for Access Controller List and is about controlling what features users have access to do in your organization.
</div>
<div>
    <div><a href="/acl/group">Manage User Groups</a></div>
    <ul>
        <li><a href="acl/group">View Groups</a></li>
        <li>Create Group</li>
        <li>Update Group - View the list of groups and click the edit action</li>
        <li>Remove Group - View the list of groups and click the remove action</li>
    </ul>
</div>