<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Rental Mgr') ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->appendStylesheet($this->basePath() . '/css/bootstrap.css')
        ->appendStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->appendStylesheet($this->basePath() . '/css/style.css')
        ->appendStylesheet($this->basePath() . '/css/overcast/jquery-ui-1.10.3.custom.min.css')
        ->appendStylesheet($this->basePath() . '/css/cfm/cfm.menu.css')
    ; ?>


    <!-- Scripts -->
    <?php echo $this->headScript()
        ->appendFile($this->basePath() . '/js/jquery/jquery.min.js')
        ->appendFile($this->basePath() . '/js/jquery/jquery-ui-1.10.3.custom.js')
        ->appendFile($this->basePath() . '/js/cfm/cfm.menu.js')

    ; ?>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <div id="logo"><a class="navbar-brand" href="<?php echo $this->url('home') ?>"><span id="block1">Rental</span><span id="block2">Mgr</span></a></div>
        </div>

    </div>
</nav>
<div class="container">
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; 2013 - <?php echo date('Y') ?> by Clay Feet Media, LLC. <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
